server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true 
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-studydb.c3tliadgbsoo.ap-northeast-2.rds.amazonaws.com:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
    
   
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      


  jackson:
    serialization:
      fail-on-empty-beans: false
          
    
#mybatis:
#  mapper-locations:
#  - /mappers/*.xml
#
#file:
#  path: C:/TeamProject/workspace/git/worksout-TeamProject/upload/
#  downloadPath:  C:/TeamProject/workspace/git/worksout-TeamProject/download/
  
